### PR TITLE
Alternative to 'get-hash'

### PR DESCRIPTION
**Pull request by NeilCollinsMS**
'get-hash' did not work in my instance, but get-filehash worked flawlessly.

### CODE REVIEW

**Review by deargle — COMMENTED** [review]
Do you mean to _replace_ get-hash with get-filehash, rather than append?

**Comment by NeilCollinsMS** [comment]
Yes, I meant replace. get-hash may work, but if it does not, _replace_ it with filehash

**Comment by deargle** [comment]
I think `get-hash` is a bygone function, and `get-filehash` is the new thing to use. Can you update your PR to just straight-up replace with get-filehash in the description?

Note that you can update the PR by doing this: "Add more commits by pushing to the patch-1 branch on NeilCollinsMS/security-assignments."

**Comment by deargle** [comment]
I award you 50 gryffindor points. :tada: thanks for this!

**Pull request merged**
